In [10]:
print('Data Science')
a=3
b=7
print(a+b)

Data Science
10


# heading1

## heading2    #is used for heading purpose

- (- is used for listing)

- 

1. A
2. 

run- ctrl+enter   and shift+ enter
add cell: +
            esc + b


# Numpy  (LIBRARY)


- Used for numerical python
- computing/statistical
- homogenous (data type should be same eithere number or alphabet can't be mix)

In [22]:
abc=[5,6,7,8,'data']
print(abc)

[5, 6, 7, 8, 'data']


In [28]:
!pip install numpy

In [5]:
import numpy as np

In [45]:
x= np.array([5,7,4,9,11])
print(x)

[ 5  7  4  9 11]


## functions
1. np.sum()
2. np.prod()
3. np.min()
4. np.max()
5. np.mean()
   

1. indexing
2. slicing
3. attributes, shape, size, ndim, type

In [41]:
#slicing             x[startindex:stopindex]
#x syntax is [start index: stop index: step]   #by default is 1
x=np.array([5,6,7,8,3,1])
print(x[1:5])

print(x[:5:2])

print(x[: :])

print(x[::-1])
print(x[1: -1])
print(x[-2:1])
print(x[-2:1:-1])

[6 7 8 3]
[5 7 3]
[5 6 7 8 3 1]
[1 3 8 7 6 5]
[6 7 8 3]
[]
[3 8 7]


In [ ]:
#modification
