In [10]:
print('Data Science')
a=3
b=7
print(a+b)

Data Science
10


# heading1

## heading2    #is used for heading purpose

- (- is used for listing)

- 

1. A
2. 

run- ctrl+enter   and shift+ enter
add cell: +
            esc + b


# Numpy  (LIBRARY)


- Used for numerical python
- computing/statistical
- homogenous (data type should be same eithere number or alphabet can't be mix)

In [22]:
abc=[5,6,7,8,'data']
print(abc)

[5, 6, 7, 8, 'data']


In [28]:
!pip install numpy

In [5]:
import numpy as np

In [45]:
x= np.array([5,7,4,9,11])
print(x)

[ 5  7  4  9 11]


1. indexing
2. slicing
3. attributes, shape, size, ndim, type

In [41]:
#slicing             x[startindex:stopindex]
#x syntax is [start index: stop index: step]   #by default is 1
x=np.array([5,6,7,8,3,1])
print(x[1:5])

print(x[:5:2])

print(x[: :])

print(x[::-1])
print(x[1: -1])
print(x[-2:1])
print(x[-2:1:-1])

[6 7 8 3]
[5 7 3]
[5 6 7 8 3 1]
[1 3 8 7 6 5]
[6 7 8 3]
[]
[3 8 7]


In [43]:
#modification
print(x)

[5 6 7 8 3 1]


In [45]:
x[3]=11
print(x)

[ 5  6  7 11  3  1]


In [47]:
#copying
y=x[0:3]
print(y)

[5 6 7]


In [49]:
y[0]=15
print(y)

[15  6  7]


In [51]:
print(x)

[15  6  7 11  3  1]


In [55]:
#copy view   .copy function is used to create independent memory location else store in same location
x=np.array([5,6,7,8,3,1])

y=x[0:3].copy()
print(y)

[5 6 7]


In [57]:
y[1]=19
print(y)

[ 5 19  7]


In [59]:
print(x)

[5 6 7 8 3 1]


## functions
1. np.sum()
2. np.prod()
   
4. np.min()
5. np.max()
   
7. np.mean()
8. np.std()

10. np.median()
11. np.sort()
12. np.unique()

In [112]:
x=np.array([5,2,7,13,3,1])


sum=np.sum(x)
# print(sum)
print(f'Sum={sum}')

prod=np.prod(x)
print(f'Product={prod}')

min=np.min(x)
print(min)

max=np.max(x)
print(max)
    
std=np.std(x)
print(std)

median=np.median(x)
print(median)

Sum=31
Product=2730
1
13
4.017323597731316
4.0


In [120]:
mean=np.mean(x)
print(f'Mean={mean}')

mean=np.mean(x)
print(f'Mean={mean:.2f}')

mean=np.mean(x)
print(f'Mean={mean:.4f}')

Mean=5.166666666666667
Mean=5.17
Mean=5.1667


In [122]:
#sorting
sorted = np.sort(x)
print(sorted) 

[ 1  2  3  5  7 13]


In [128]:
#to check the documentation
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.

    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.

        .. versionchanged:: 1.15.0.
           The 'stable' option was added.

    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A sin

#array arthimetic 
np.add()
np.multiply()
np.divide()
np.floor_divide()
np.mod()
np.power()
np.sqrt()


Sort descending	np.sort(x)[::-1]

In [154]:
x=np.array([4,5,3,2])
y=np.array([2,1,4,3])

z=np.add(x,y)
print(z)

z=x+y
print(z)

p=np.divide(x,y)
print(p)

p=x/y
print(p)

g=np.floor_divide(x,y)
print(g)

g=np.mod(x,y)
print(g)

g=np.power(x,y)
print(g)

g=np.sqrt(x)
print(g)

g=np.power(y,3)
print(g)

#if number of dimension is not same then also get error


[6 6 7 5]
[6 6 7 5]
[2.         5.         0.75       0.66666667]
[2.         5.         0.75       0.66666667]
[2 5 0 0]
[0 0 3 2]
[16  5 81  8]
[2.         2.23606798 1.73205081 1.41421356]
[ 8  1 64 27]


In [ ]:
#Broadcasting 
