In [10]:
print('Data Science')
a=3
b=7
print(a+b)

Data Science
10


# heading1

## heading2    #is used for heading purpose

- (- is used for listing)

- 

1. A
2. 

run- ctrl+enter   and shift+ enter
add cell: +
            esc + b


# Numpy  (LIBRARY)


- Used for numerical python
- computing/statistical
- homogenous (data type should be same eithere number or alphabet can't be mix)

In [22]:
abc=[5,6,7,8,'data']
print(abc)

[5, 6, 7, 8, 'data']


In [28]:
!pip install numpy

In [5]:
import numpy as np

In [45]:
x= np.array([5,7,4,9,11])
print(x)

[ 5  7  4  9 11]


1. indexing
2. slicing
3. attributes, shape, size, ndim, type

In [41]:
#slicing             x[startindex:stopindex]
#x syntax is [start index: stop index: step]   #by default is 1
x=np.array([5,6,7,8,3,1])
print(x[1:5])

print(x[:5:2])

print(x[: :])

print(x[::-1])
print(x[1: -1])
print(x[-2:1])
print(x[-2:1:-1])

[6 7 8 3]
[5 7 3]
[5 6 7 8 3 1]
[1 3 8 7 6 5]
[6 7 8 3]
[]
[3 8 7]


In [43]:
#modification
print(x)

[5 6 7 8 3 1]


In [45]:
x[3]=11
print(x)

[ 5  6  7 11  3  1]


In [47]:
#copying
y=x[0:3]
print(y)

[5 6 7]


In [49]:
y[0]=15
print(y)

[15  6  7]


In [51]:
print(x)

[15  6  7 11  3  1]


In [55]:
#copy view   .copy function is used to create independent memory location else store in same location
x=np.array([5,6,7,8,3,1])

y=x[0:3].copy()
print(y)

[5 6 7]


In [57]:
y[1]=19
print(y)

[ 5 19  7]


In [59]:
print(x)

[5 6 7 8 3 1]


## functions
1. np.sum()
2. np.prod()
   
4. np.min()
5. np.max()
   
7. np.mean()
8. np.std()

10. np.median()
11. np.sort()
12. np.unique()

In [112]:
x=np.array([5,2,7,13,3,1])


sum=np.sum(x)
# print(sum)
print(f'Sum={sum}')

prod=np.prod(x)
print(f'Product={prod}')

min=np.min(x)
print(min)

max=np.max(x)
print(max)


    
std=np.std(x)
print(std)

median=np.median(x)
print(median)

Sum=31
Product=2730
1
13
4.017323597731316
4.0


In [120]:
mean=np.mean(x)
print(f'Mean={mean}')

mean=np.mean(x)
print(f'Mean={mean:.2f}')

mean=np.mean(x)
print(f'Mean={mean:.4f}')

Mean=5.166666666666667
Mean=5.17
Mean=5.1667
